#!/bin/sh

BASEDIR="$(dirname "$0")"

cd "$BASEDIR"
echo "Updating submodules..."
git submodule update --init --recursive
git submodule update --recursive --remote

echo "Preparing directories..."
mkdir -p "$HOME/pictures"
mkdir -p "$HOME/dl"

echo "Using stow to deploy file symlinks..."
stow -R -t ~ home_* --override=* --verbose=0

echo "Done! Run './install' to install needed packages!"
