#!/bin/sh

BASEDIR="$(dirname "$0")"

function needs() {
	(pacman -Qi | grep "$1" -q) && return 1 || return 0
}

pushd
cd /tmp

echo "Installing git..."
needs git && sudo pacman -S git

echo "Installing yay..."
if [ needs yay ]
then
	git clone https://aur.archlinux.org/yay.git
	pushd
	cd yay
	makepkg -si
	popd
	rm -rf yay
fi

PACKAGES="alacritty brave-bin bspwm sxhkd neofetch dunst picom-git polybar-git mpd xorg-xinit ncpamixer-git neovim nerd-fonts-git noto-fonts-emoji rofi rofi-calc rofi-emoji gimp maim glava zsh"
echo "Installing $PACKAGES"
yay --needed -S $PACKAGES

echo "Installing oh-my-zsh..."
[ ! -d "$HOME/.oh-my-zsh" ] && sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo "Setting up oh-my-zsh plugins..."
pushd
cd "$HOME/.oh-my-zsh/custom/plugins"
git clone https://github.com/zsh-users/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
popd

popd
