#!/bin/sh

PROTON_USE_NTSYNC=1 PRESSURE_VESSEL_FILESYSTEMS_RO="$MANGOHUD_CONFIGFILE:$VKBASALT_CONFIG_FILE" MANGOHUD_DLSYM=1 nice -n18 gamemoderun mangohud "$@"
# pkill picom
# PRESSURE_VESSEL_FILESYSTEMS_RO="$MANGOHUD_CONFIGFILE:$VKBASALT_CONFIG_FILE" MANGOHUD_DLSYM=1 mangohud "$@"
# exec picom --experimental-backends &
