#! /bin/sh

# start sxhkd
SXHKDRC=$(cat ~/.config/sxhkd/sxhkdrc.raw)
sh -c "echo -e \"$SXHKDRC\" > ~/.config/sxhkd/sxhkdrc"
(killall sxhkd; sxhkd) &

# start dunst
(killall dunst; dunst) &

# start mpd_discord_richpresence
(killall mpd_discord_richpresence; mpd_discord_richpresence) &

# start noaftodo daemon
(noaftodo -k; noaftodo -d) &

# set keyboard mappings
setxkbmap -layout "us,ru,gr,fr" -option "grp:alt_space_toggle" &

# run polybar
(killall polybar; polybar flatbar -c /home/greg/.config/polybar/flat-config-bspwm) &

# bring focused windows on top
(killall bspc-focused-ontop; ~/scripts/bspc-focused-ontop.sh) &

# run nm-applet
(killall nm-applet; nm-applet) &

# run qlipper
# (killall qlipper; qlipper) &

# run picom
(killall picom; picom --experimental-backend --dbus) &

# optimus-manager-qt
# (killall optimus-manager-qt; optimus-manager-qt) &

# set wallpapers
hsetroot -cover $DBG &

# set cursor
xsetroot -cursor_name left_ptr &

bspc monitor -d 01 02 03 04 05 06 07 08 09 10 # 11 12 13 14 15 16 17 18 19 20

# don't care about unplugged/removed mmonitors
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config border_width         1
bspc config window_gap          0
bspc config bottom_padding 5
bspc config right_padding 5
bspc config left_padding 5
bspc config top_padding 25

bspc config single_monocle false

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config normal_border_color '#454646'
bspc config active_border_color '#0080aa'
bspc config focused_border_color '#0080aa'

bspc rule -a Zathura state=tiled

bspc rule -a qbittorrent desktop='^1'

bspc rule -a Brave-browser desktop='^2'
bspc rule -a firefox desktop='^2'

bspc rule -a Gimp desktop='^5'
bspc rule -a Inkscape desktop='^5'
bspc rule -a krita desktop='^5'

bspc rule -a Steam desktop='^6'
bspc rule -a epicgameslauncher.exe desktop='^6'
bspc rule -a Lutris desktop='^6'
bspc rule -a heroic desktop='^6'

bspc rule -a Picture-in-picture state=floating sticky=on

bspc rule -a Onboard state=floating sticky=on

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
