#!/bin/sh

# start sxhkd
# Check for $MOD and $TERMINAL, if unset, use default:
if [ "$MOD" == "" ]; then
	export MOD="super"
fi
if [ "$TERMINAL" == ""]; then
	export TERMINAL="xterm"
fi
SXHKDRC=$(cat ~/.config/sxhkd/sxhkdrc.raw)
sh -c "echo -e \"$SXHKDRC\" > ~/.config/sxhkd/sxhkdrc"
(killall sxhkd; sxhkd) &

# start dunst
(killall dunst; dunst) &

# start polkit
(ps -e | grep polkitd || rofi-polkit-agent) &

# start mpd_discord_richpresence
(killall mpd_discord_richpresence; mpd_discord_richpresence) &

# start noaftodo daemon
(noaftodo -k; noaftodo -d) &

# start rofi polkit agent
(killall rofi-polkit-agent; rofi-polkit-agent) &

# set keyboard mappings
setxkbmap -layout us -option grab:break_actions&

# nvidia-settings picom hack
# nvidia-settings -a 'AllowFlipping=0'

# run polybar(s)
(
sleep 1
killall polybar
echo 1 > /tmp/ipline
function plb() {
    polybar $1$primary -c /home/greg/.config/polybar/config &
}
function parsemon() {
    export MONITOR="$(echo "$MONSTR" | sed 's/.* //')"
    MONRGX='.*: .* \([0-9]*\)\/\([0-9]*\)x\([0-9]*\)\/\([0-9]*\)+[0-9]*+[0-9]*.*'
    export MON_PX_X="$(echo "$MONSTR" | sed "s/$MONRGX/\1/")"
    export MON_MM_X="$(echo "$MONSTR" | sed "s/$MONRGX/\2/")"
    export MON_PX_Y="$(echo "$MONSTR" | sed "s/$MONRGX/\3/")"
    export MON_MM_Y="$(echo "$MONSTR" | sed "s/$MONRGX/\4/")"

    if [ $MON_PX_X -le $MON_PX_Y ] && [ $MON_MM_X -gt $MON_MM_Y ]
    then
        TEMP=$MON_MM_X
        MON_MM_X=$MON_MM_Y
        MON_MM_Y=$TEMP
    fi

    if [ "$primary" = "_primary" ]
    then
        export BAR_RIGHT_OFFSET=$(($MON_PX_X - 635 - 5))
        export BAR_CENTER_OFFSET=$(( ($MON_PX_X - 750) / 2 ))
    else
        export BAR_RIGHT_OFFSET=$(($MON_PX_X - 550 - 5))
        export BAR_CENTER_OFFSET=$(( ($MON_PX_X - 600) / 2 ))
    fi
}
MONSTR=$(xrandr --listactivemonitors | grep ': +\*')
primary=
parsemon
plb left
plb right
primary=_primary
parsemon
plb center
primary=
parsemon
xrandr --listactivemonitors | tail -n +2 | grep -v ': +\*' | while read MONSTR
do
    parsemon
    plb left
    plb center
    plb right
done
) &

# bring focused windows on top
(killall bspc-focused-ontop.sh; ~/scripts/bspc-focused-ontop.sh) &

# run nm-applet
(killall nm-applet; nm-applet) &

# run qlipper
# (killall qlipper; qlipper) &

# run picom
(killall picom; picom --dbus) &

# optimus-manager-qt
# (killall optimus-manager-qt; optimus-manager-qt) &

# set wallpapers
hsetroot -extend $D_BACKGROUND -root &
~/scripts/livewp_stop.sh
~/scripts/livewp.sh

# set cursor
xsetroot -cursor_name left_ptr &

for MON in $(xrandr | grep " connected" | cut -d" " -f1); do
	bspc monitor "$MON" -d 1 2 3 4 5 6 7 8 9 0
done

# don't care about unplugged/removed mmonitors
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config border_width        1
bspc config window_gap          5
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0
bspc config top_padding 25

bspc config single_monocle false

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config focus_follows_pointer true

bspc config normal_border_color '#454646'
bspc config active_border_color '#21c7a8'
bspc config focused_border_color '#21c7a8'

bspc config pointer_motion_interval 5	# My monitor is 165 Hz

bspc rule -a Zathura state=tiled

bspc rule -a qbittorrent desktop='1.local'

bspc rule -a qutebrowser desktop='2.local'
bspc rule -a Brave-browser desktop='2.local'
bspc rule -a firefox desktop='2.local'

bspc rule -a Gimp desktop='5.local'
bspc rule -a Inkscape desktop='5.local'
bspc rule -a krita desktop='5.local'

bspc rule -a Steam desktop='6.local'
bspc rule -a epicgameslauncher.exe desktop='6.local'
bspc rule -a Lutris desktop='6.local'
bspc rule -a heroic desktop='6.local'

bspc rule -a "*:*:Picture in picture" state=floating sticky=on

bspc rule -a Onboard state=floating sticky=on

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
